#!/usr/bin/env bash
# Run on the preview host after deploy (see scripts/preview-gha-deploy.sh).
# Writes nginx location snippet for https://<public-host>/<pr>/ → loopback preview-web port, then reloads edge.
# One-time setup: copy infra/preview/edge/ to ~/preview-edge/ and docker compose up -d (see docs/pr-preview-environments.md).
set -euo pipefail

PR="${1:?PR number required}"
PORT="${2:?loopback port required}"

SNIP_DIR="${PREVIEW_EDGE_SNIPPET_DIR:-${HOME}/preview-edge/snippets}"
COMPOSE_FILE="${PREVIEW_EDGE_COMPOSE_FILE:-${HOME}/preview-edge/docker-compose.yml}"

mkdir -p "${SNIP_DIR}"

# Strip /{pr}/ prefix at the edge so inner nginx-preview still serves / and /api/.
cat >"${SNIP_DIR}/pr-${PR}.conf" <<EOF
# Generated by preview-edge-write-snippet.sh — do not edit by hand
location = /${PR} {
  return 302 /${PR}/;
}
location ^~ /${PR}/ {
  rewrite ^/${PR}/(.*)\$ /\$1 break;
  proxy_pass http://127.0.0.1:${PORT};
  proxy_http_version 1.1;
  proxy_set_header Host \$host;
  proxy_set_header X-Real-IP \$remote_addr;
  proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
  proxy_set_header X-Forwarded-Proto \$scheme;
}
EOF

if [ -f "${COMPOSE_FILE}" ]; then
  COMPOSE_DIR="$(dirname "${COMPOSE_FILE}")"
  COMPOSE_BASE="$(basename "${COMPOSE_FILE}")"
  (
    cd "${COMPOSE_DIR}" || exit 1
    if docker compose version >/dev/null 2>&1; then
      docker compose -f "${COMPOSE_BASE}" up -d
      docker compose -f "${COMPOSE_BASE}" exec -T preview-edge nginx -s reload || true
    elif command -v docker-compose >/dev/null 2>&1; then
      docker-compose -f "${COMPOSE_BASE}" up -d
      docker-compose -f "${COMPOSE_BASE}" exec -T preview-edge nginx -s reload || true
    else
      echo "preview-edge: docker compose not found on host" >&2
      exit 1
    fi
  )
else
  echo "preview-edge: ${COMPOSE_FILE} not found — snippet written to ${SNIP_DIR}; start or reload edge nginx when ready."
fi
