import { JwtService } from './jwt.service';
import { UserRole } from '@equip-track/shared';
import { generateKeyPairSync } from 'crypto';
import * as jwt from 'jsonwebtoken';

const { mockSend } = jest.requireMock<{
  mockSend: jest.Mock;
}>('@aws-sdk/client-secrets-manager');

jest.mock('@aws-sdk/client-secrets-manager', () => {
  const mockSend = jest.fn();
  return {
    SecretsManagerClient: jest.fn().mockImplementation(() => ({
      send: mockSend,
    })),
    GetSecretValueCommand: jest.fn().mockImplementation(
      (input: { SecretId: string }) => ({ input })
    ),
    mockSend,
  };
});

let mockPrivateKey: string;
let mockPublicKey: string;

beforeAll(() => {
  const { privateKey, publicKey } = generateKeyPairSync('rsa', {
    modulusLength: 2048,
    publicKeyEncoding: { type: 'spki', format: 'pem' },
    privateKeyEncoding: { type: 'pkcs8', format: 'pem' },
  });
  mockPrivateKey = privateKey;
  mockPublicKey = publicKey;
});

describe('JwtService', () => {
  let jwtService: JwtService;

  beforeEach(() => {
    jest.clearAllMocks();

    mockSend.mockImplementation(
      (command: { input?: { SecretId?: string } }) => {
        const secretId = command.input?.SecretId ?? '';
        if (secretId.includes('private-key')) {
          return Promise.resolve({ SecretString: mockPrivateKey });
        }
        if (secretId.includes('public-key')) {
          return Promise.resolve({ SecretString: mockPublicKey });
        }
        return Promise.reject(new Error('Secret not found'));
      }
    );

    jwtService = new JwtService();
  });

  describe('generateToken', () => {
    it('should generate a valid JWT token', async () => {
      const userId = 'user123';
      const orgIdToRole = {
        org456: UserRole.Admin,
        org789: UserRole.Customer,
      };

      const token = await jwtService.generateToken(userId, orgIdToRole);

      expect(typeof token).toBe('string');
      expect(token.split('.')).toHaveLength(3);

      const decoded = jwt.decode(token) as Record<string, unknown>;
      expect(decoded.sub).toBe(userId);
      expect(decoded.orgIdToRole).toEqual(orgIdToRole);
      expect(decoded.iat).toBeDefined();
      expect(decoded.exp).toBeDefined();

      const expectedExp = Math.floor(Date.now() / 1000) + 7 * 24 * 60 * 60;
      expect(
        Math.abs((decoded.exp as number) - expectedExp)
      ).toBeLessThan(60);
    });

    it('should handle empty organization roles', async () => {
      const userId = 'user123';
      const orgIdToRole = {};

      const token = await jwtService.generateToken(userId, orgIdToRole);

      expect(typeof token).toBe('string');
      const decoded = jwt.decode(token) as Record<string, unknown>;
      expect(decoded.sub).toBe(userId);
      expect(decoded.orgIdToRole).toEqual({});
    });

    it('should handle AWS Secrets Manager errors', async () => {
      mockSend.mockRejectedValue(new Error('AWS Error'));

      await expect(
        jwtService.generateToken('user', { org: UserRole.Customer })
      ).rejects.toThrow('Failed to generate authentication token');
    });
  });

  describe('validateToken', () => {
    it('should validate a token generated by the service', async () => {
      const userId = 'user123';
      const orgIdToRole = {
        org456: UserRole.WarehouseManager,
        org789: UserRole.Customer,
      };

      const token = await jwtService.generateToken(userId, orgIdToRole);

      const payload = await jwtService.validateToken(token);

      expect(payload.sub).toBe(userId);
      expect(payload.orgIdToRole).toEqual(orgIdToRole);

      const decoded = jwt.decode(token) as Record<string, unknown>;
      expect(decoded.sub).toBe(userId);
      expect(decoded.orgIdToRole).toEqual(orgIdToRole);
    });

    it('should reject invalid tokens', async () => {
      await expect(
        jwtService.validateToken('invalid.jwt.token')
      ).rejects.toThrow('Invalid authentication token');
    });

    it('should reject expired tokens', async () => {
      await expect(jwtService.validateToken('expired')).rejects.toThrow(
        'Invalid authentication token'
      );
    });
  });

  describe('getUserIdFromToken', () => {
    it('should extract user ID from valid token', async () => {
      const userId = 'user123';
      const orgIdToRole = { org456: UserRole.Admin };
      const token = await jwtService.generateToken(userId, orgIdToRole);

      const extractedUserId = jwtService.getUserIdFromToken(token);

      expect(extractedUserId).toBe(userId);
    });

    it('should return null for invalid token', () => {
      const extractedUserId = jwtService.getUserIdFromToken('invalid');

      expect(extractedUserId).toBeNull();
    });
  });

  describe('isTokenExpired', () => {
    it('should return false for valid token', async () => {
      const token = await jwtService.generateToken('user', {
        org: UserRole.Customer,
      });

      const isExpired = jwtService.isTokenExpired(token);

      expect(isExpired).toBe(false);
    });

    it('should return true for invalid token format', () => {
      const isExpired = jwtService.isTokenExpired('invalid');

      expect(isExpired).toBe(true);
    });
  });

  describe('caching', () => {
    it('should cache private key to avoid repeated AWS calls', async () => {
      const userId = 'user123';
      const orgIdToRole = { org456: UserRole.Customer };

      await jwtService.generateToken(userId, orgIdToRole);
      await jwtService.generateToken(userId, orgIdToRole);

      expect(mockSend.mock.calls.filter((c) => {
        const cmd = c[0] as { input?: { SecretId?: string } };
        return cmd.input?.SecretId?.includes('private-key');
      })).toHaveLength(1);
    });
  });
});
